/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class CalorieApp {
    
    public static void main(String[] args) {
             InputGui input = new InputGui();
       
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                input.setVisible(true);
            }
        });  
          
         
           
    }
}
