
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;

/**
 *
 * @author chinjila
 */
public class OutputGui extends javax.swing.JFrame {

        /**
         * Creates new form OutputGui
         */
        private javax.swing.JLabel bulkCalorieLabel;
        private java.awt.Panel bulkPanel;
        private javax.swing.JLabel bulkTitleLabel;
        private java.awt.Label calorieStaticLabel;
        private javax.swing.JLabel cutCalorieLabel;
        private javax.swing.JLabel cutTitleLabel;
        private javax.swing.JFrame jFrame1;
        private javax.swing.JFrame jFrame2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JLabel secondCalorieStaticLabel;

        private int height;
        private int weight;
        private int age;
        private double factor;
        @SuppressWarnings("unused")
        private boolean male = true;
        private double BMR = 0.0;

        public OutputGui(int height, int weight, int age, double factor, boolean male) {
                initComponents();
                bulkPanel.setBackground(Color.WHITE);
                this.height = height;
                this.weight = weight;
                this.age = age;
                this.factor = factor;
                this.male = male;

                if (male == true) {
                        BMR = calcMaleBMR();
                } else {
                        BMR = calcFemaleBMR();
                }

                setBulkCalories();
                setCutCalories();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jFrame1 = new javax.swing.JFrame();
                jTextField1 = new javax.swing.JTextField();
                jFrame2 = new javax.swing.JFrame();
                bulkPanel = new java.awt.Panel();
                bulkTitleLabel = new javax.swing.JLabel();
                bulkCalorieLabel = new javax.swing.JLabel();
                secondCalorieStaticLabel = new javax.swing.JLabel();
                cutTitleLabel = new javax.swing.JLabel();
                cutCalorieLabel = new javax.swing.JLabel();
                calorieStaticLabel = new java.awt.Label();

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                jScrollPane1.setViewportView(jTable1);

                javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
                jFrame1.getContentPane().setLayout(jFrame1Layout);
                jFrame1Layout.setHorizontalGroup(
                                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 400, Short.MAX_VALUE));
                jFrame1Layout.setVerticalGroup(
                                jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 300, Short.MAX_VALUE));

                jTextField1.setText("jTextField1");

                javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
                jFrame2.getContentPane().setLayout(jFrame2Layout);
                jFrame2Layout.setHorizontalGroup(
                                jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 400, Short.MAX_VALUE));
                jFrame2Layout.setVerticalGroup(
                                jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 300, Short.MAX_VALUE));

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                bulkTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                bulkTitleLabel.setText("Bulking:");

                bulkCalorieLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                bulkCalorieLabel.setText("3000 ");

                secondCalorieStaticLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                secondCalorieStaticLabel.setText("Calories");

                javax.swing.GroupLayout bulkPanelLayout = new javax.swing.GroupLayout(bulkPanel);
                bulkPanel.setLayout(bulkPanelLayout);
                bulkPanelLayout.setHorizontalGroup(
                                bulkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bulkPanelLayout.createSequentialGroup()
                                                                .addGroup(bulkPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(bulkPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(71, 71, 71)
                                                                                                .addGroup(bulkPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(bulkCalorieLabel)
                                                                                                                .addComponent(bulkTitleLabel)))
                                                                                .addGroup(bulkPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(55, 55, 55)
                                                                                                .addComponent(secondCalorieStaticLabel)))
                                                                .addContainerGap(46, Short.MAX_VALUE)));
                bulkPanelLayout.setVerticalGroup(
                                bulkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bulkPanelLayout.createSequentialGroup()
                                                                .addGap(22, 22, 22)
                                                                .addComponent(bulkTitleLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(bulkCalorieLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                32,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(secondCalorieStaticLabel)
                                                                .addGap(65, 65, 65)));

                cutTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                cutTitleLabel.setText("Cutting:");

                cutCalorieLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                cutCalorieLabel.setText("3000");

                calorieStaticLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
                calorieStaticLabel.setText("Calories");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(48, 48, 48)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(cutTitleLabel)
                                                                                                                .addComponent(cutCalorieLabel)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(29, 29, 29)
                                                                                                .addComponent(calorieStaticLabel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                50,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(bulkPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(cutTitleLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                25,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(55, 55, 55)
                                                                .addComponent(cutCalorieLabel)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(calorieStaticLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 62, Short.MAX_VALUE))
                                                .addComponent(bulkPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }

        public double calcMaleBMR() {
                double maleBMR = (10 * weight) + (6.25 * height) - (5 * age) + 5;
                return maleBMR;

        }

        public double calcFemaleBMR() {
                double femaleBMR = (10 * weight) + (6.25 * height) - (5 * age) - 161;
                return femaleBMR;

        }

        public double calcSurplus() {
                double TDEE = BMR * factor;
                double surplus = TDEE * 1.1;
                return Math.ceil(surplus);
        }

        public double calcDeficit() {
                double TDEE = BMR * factor;
                double deficit = TDEE - 500;
                return Math.ceil(deficit);
        }

        public void setBulkCalories() {

                bulkCalorieLabel.setText(String.valueOf((int) calcSurplus()));

        }

        public void setCutCalories() {

                cutCalorieLabel.setText(String.valueOf((int) calcDeficit()));

        }

}
